# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_sander", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="image",
            field=models.ImageField(upload_to="static/mailguner/images/"),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="template",
            field=models.FileField(upload_to="static/mailguner/templates/"),
        ),
    ]
