# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_sander", "0002_auto_20221117_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="template",
            field=models.FilePathField(path="mail_sander/templates/mail_sander"),
        ),
    ]
