# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-18 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mail_sander", "0004_auto_20221117_1921"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
